### ISSUE TITLE
Adding max_length to multiline codec

### ISSUE THREAD

**Issue by anandaverma** [elasticsearch/logstash#1292]
Most of the time there is no control on no. of lines comes in a stack trace and it is main cause of java heap issue when multiline codec is used. It would be better if we add a max_length property to multiline code to allow only fewer lines which are relevant to get pushed to the input queue.
``` 
log4j, [2014-04-20T02:42:07.970]  WARN: org.elasticsearch.transport.netty: [Thor(App)] exception caught on transport layer [[id: 0x06f37535, /10.2.17.110:41482 => /10.2.17.143:9300]], closing connection
java.lang.OutOfMemoryError: Java heap space
log4j, [2014-04-20T02:49:26.843]  WARN: org.elasticsearch.transport.netty: [Thor(App)] exception caught on transport layer [[id: 0xb845a618, /10.2.17.143:35101 => /10.2.17.110:9303]], closing connection
java.lang.OutOfMemoryError: Java heap space
log4j, [2014-04-20T02:49:41.050]  WARN: org.elasticsearch.transport.netty: [Thor(App)] exception caught on transport layer [[id: 0xb845a618, /10.2.17.143:35101 :> /10.2.17.110:9303]], closing connection
```

**Comment by untergeek** [comment]
Can you confirm this is stack trace related?  Logstash can ingest 5mb documents (and probably much bigger) and transport them to Elasticsearch with no difficulty.  Elasticsearch itself is capable of much larger documents than that, even.  If the netty transport is truly having an OOM, it's a big deal.  Also, Elasticsearch has incremented its netty version several times in the last 9 months.

I'm willing to accept that this may be multiline related, but it may also be that the multiline message never breaks, so it's actually multiple multiline messages (this behavior has been observed in other cases) rather than one big stack trace.

In any case, no further requests have been made to address this in 9 months, so I'm closing it.  Please feel free to re-open with more details.

**Comment by colinsurprenant** [comment]
this relates to logstash-plugins/logstash-codec-multiline#4
