### ISSUE TITLE
http output plugin does not support codec ?

### ISSUE THREAD

**Issue by SkyRocknRoll** [elasticsearch/logstash#1438]
The document here http://logstash.net/docs/1.4.1/outputs/http says it supports codec. 
In the code i am not able to find code related to codec config. 

I have given json_lines as codec but it does not work. 
If i am doing something wrong please let me know. 

Thanks 
Yuva

**Comment by untergeek** [comment]
Hi.  Sorry to keep you waiting for so long.

The http output plugin has been moved to https://github.com/logstash-plugins/logstash-output-http

This plugin does not support a codec, but rather uses `@format` instead.  See lines 46-54:

https://github.com/logstash-plugins/logstash-output-http/blob/master/lib/logstash/outputs/http.rb#L46-L54

```
  # Set the format of the http body.
  #
  # If form, then the body will be the mapping (or whole event) converted
  # into a query parameter string, e.g. `foo=bar&baz=fizz...`
  #
  # If message, then the body will be the result of formatting the event according to message
  #
  # Otherwise, the event is sent as json.
  config :format, :validate => ["json", "form", "message"], :default => "json"
```

Please address any other issues to the new plugin repo: https://github.com/logstash-plugins/logstash-output-http

**Comment by fcntl** [comment]
Can can an output not support a codec? Isn't that the whole point of logstash? What a joke.

**Comment by jordansissel** [comment]
@fcntl I can understand your frustrations. This looks like an area we could improve. Would you mind opening a ticket about adding codec support?

**Comment by kehao95** [comment]
Is there any update on this issue?
I saw codec in 'Available configuration options' Doc
[plugins-outputs-http](https://www.elastic.co/guide/en/logstash/1.5/plugins-outputs-http.html)
I want to set the Http body using codec. But there are only `json, form, message` in format options, missing `codec`.

If `codec` is still unavailable, I may suggest remove it from the Doc. For it's confusing.
If `codec` is available, I may suggest providing an example in Doc.
Please forgive me if I made any mistake.

PS: 
I know RTFM. But after searching for quite a while. I can't find an example about this online and doc.
This issue is one of top results of keywords `logstash http output codec` in google.
