### ISSUE TITLE
Logstash input file path match dated directory does not work

### ISSUE THREAD

**Issue by chelsu** [elasticsearch/logstash#2335]
I see an issue matching input file path in Logstash 1.4.2.

I am trying to match all files in a dated directory path.
Example file to match: 
/usr/tmp/input/2015/01/09/ tx/FileA-2015-01-09.tx
/usr/tmp/input/2015/01/09/ tx/FileB-2015-01-09.tx

I used following path in the logstash config
path => "/usr/tmp/input/%{+YYYY}/%{+MM}/%{+dd}/tx/*

configtest was ok. But I just see glob is empty in the verbose output. 

Using same pattern for specifying index in elasticsearch output works.

**Comment by jordansissel** [comment]
Sorry for the confusion. This syntax doesn't tell the file input to watch things based on dates. It tells logstashl ook for files in a directory literally "/usr/tmp/input/%{+YYYY}/%{+MM}/%{+dd}/tx/" - the `%{...}` syntax has no meaning in the `path` setting.

An alternative would be to use `/usr/tmp/input/*/*/*/tx/*`

**Comment by jordansissel** [comment]
I have considered adding date-pattern support to the file input, but nothing has been planned or designed yet.

**Comment by chelsu** [comment]
Thanks for the information. I have been trying a lot of permutations and nothing worked.

**Comment by elisiano** [comment]
What is currently the preferred way to achieve this?
I could cook up something in puppet in order to change the configuration everyday, but is there a better way to do so?

**Comment by jordansissel** [comment]
Can you help me understand what you're trying to do? What doesn't work about using wildcards?

**Comment by elisiano** [comment]
I have a centralized rsyslog server with all logs organized in directories by hostname/date.

I am currently using wildcards, but it's hundreds of thousands files and logstash does not reliably ships events to elasticsearch (and the number goes up every day). 

The input file path contains <prefix>/**/* to expand all dirs and files and it starts from the beginning of each file (to import historical data).

I would like for logstash to keep open only the recent files and not all.

**Comment by balooka** [comment]
I have a similar situation as @elisiano.
Current approaches to resolve the issue I have found:
* Comment in logstash JIRA [LOGSTASH-608](https://logstash.jira.com/browse/LOGSTASH-608)
  there is a reference to a "potential workaround" there 
* setting up a separate path, containing symlinks that are updated by a cron job
  so that /data/logs/live is a symlink to /data/logs/YYYYMMdd, updated daily

The 2nd one is currently implemented, the one referenced in the jira I haven't tested yet

But I'd definitely favor being able to manage the filtering all in the logstash config in a clear way

**Comment by shiv4289** [comment]
Add the plugin https://github.com/logstash-plugins/logstash-output-file and this works.

**Comment by oyld** [comment]
I have the same needs of date-pattern.
