### ISSUE TITLE
add ability to have multiple index templates

### ISSUE THREAD

**Issue by jillesvangurp** [elasticsearch/logstash#2363]
Currently when using elasticsearch output, you can configure elasticsearch mapping template for a single index. It would be useful to use multiple templates to for example treat logdata for one type different than another instead of choosing a one size fits all strategy for all log data. 

For example in our case we gather some log data that is high volume, but low priority (e.g. collectd) as well as low frequency/volume data related to e.g. application logs. In this case, it would be nice to be able to have different indicices with different shard counts, replica settings, etc as well as custom mappings so that we can treat it differently.

**Comment by untergeek** [comment]
Elasticsearch supports that feature now.  You just have to take the JSON file of the template, change it accordingly, and upload it to elasticsearch with a different name.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-templates.html

Logstash's template management feature was originally included—almost exclusively—to add the `.raw` multi-field type to each string value automatically.  This was so Kibana users would be able to use `not_analyzed` fields out of the box.

Because of the complexity of managing multiple templates, and because it's technically only a simplified loader for the very robust Elasticsearch functionality, Logstash will not likely add that feature.

**Comment by suyograo** [comment]
@jillesvangurp you can overwrite what template LS uses by providing the config `template` and setting `template_overwrite` to true. 

Do you have 2 separate ES outputs for your 2 use cases?

**Comment by jillesvangurp** [comment]
Right, I currently have only one elasticsearch output. I'd like to be able to direct the data to different indices based on the type. I guess I could use multiple outputs maybe?

**Comment by untergeek** [comment]
Conditionals will make that possible:

```
output {
  if [type] == "lowpriority" {
    elasticsearch {
      ...
      template => "/path/to/lowpriority/template.json"
    }
  }
    if [type] == "highpriority" {
    elasticsearch {
      ...
      template => "/path/to/highpriority/template.json"
    }
  }
}
```
Obviously your other settings will have to go into the `...` section, but this should give you the idea.

I recommend using `protocol => "http"` with this setup, rather than the default node protocol.  Having multiple Logstash-owned ES client nodes will consume more Logstash heap memory with no noticeable benefit.

**Comment by jillesvangurp** [comment]
That looks like it should work, thanks.
