### ISSUE TITLE
Create a logstash-core gem

### ISSUE THREAD

**Issue by ph** [elasticsearch/logstash#2474]
The plugins need to have a way to define their dependencies on Logstash. (~> 1.5)
Right now we are solving this by creating a virtual `gemspec` and adding it to the `Gemspec` database.
If we create and publish a real `logstash-core` gem we will be able to remove this hack.

**Comment by electrical** [comment]
What would that logstash-core have content wise?

**Comment by colinsurprenant** [comment]
I think it should contain only `lib/` and `spec/`, not sure about `docs/`. all the rest should stay in `logstash` and would be packaging/wrapping/runtime related. in a first step we could live with just a `logstash-core.gemspec` in the current repo but eventually I'd argue to move it to its own `logstash-core` repo.

**Comment by electrical** [comment]
Any specific reason for splitting it of? i don't really see any compelling reasons for it.

**Comment by jordansissel** [comment]
@electrical the ticket description describes the hack that we can remove if we ship logstash-core as a gem.

Even prior to this ticket we had a few discussions that indicated we needed to publish a logstash gem, anyway, for the purposes of plugin development. At present, all the logstash-plugins repos have a Gemfile that pin the `logstash` dependency as coming from a `:git => ...` url. This :git source of a gem is not practical because the logstash git repo is large (80mb) and it makes it difficult to reliably switch versions of logstash (I do not put strong trust in bundler's git features). If we ship a gem, plugins can depend on logstash-core with a range of versions - something that is not possible today with the Gemfile hacks we have.

**Comment by jordansissel** [comment]
@ph any reason not to call the gem 'logstash' ?

**Comment by ph** [comment]
@jordansissel could be logstash, actually I don't have a strong opinion on the naming. I went with the *-core because we were referencing it as the `core`  vs the `runtime` bootstrap. @colinsurprenant what is your opinion on this?

**Comment by purbon** [comment]
Hi,
  logstash-core is a nice name in my opinion as it clear say is the core of logstash there, avoiding any kind of misunderstanding on the process.

**Comment by colinsurprenant** [comment]
I also prefer `logstash-core` as it differentiate from bare `logstash` which is the product/package itself. `logstash-core` as a gem clearly states that this is the core code for logstash, but not logstash itself.

**Comment by purbon** [comment]
+1 @colinsurprenant , should we build this for RC1? or do it for GA?

**Comment by colinsurprenant** [comment]
I'd like this for RC1 so that all the basic building blocks are in place before GA.

**Comment by colinsurprenant** [comment]
we need to decide on the versioning of that gem. I think it'd make sense to keep that gem version the same as the logstash release version. thoughts?

**Comment by purbon** [comment]
makes sense.

**Comment by ph** [comment]
I would go ahead with the same versioning, because it will be the public interface for plugins developpers.

**Comment by purbon** [comment]
At the end logstash will become the product this this the logstash core.

**Comment by suyograo** [comment]
Closed https://github.com/elasticsearch/logstash/pull/2629. Will create a new one to publish the RC1 version
