### ISSUE TITLE
Elasticsearch-1.1.1 with Logstash-1.4.2

### ISSUE THREAD

**Issue by Israaaaa** [elasticsearch/logstash#2601]
I was wondering, what is the reason of having Elasticsearch-1.1.1 in vendor/jar when Logstash-1.4.2 works with Elasticsearch-1.4.2? This generated an error with Kibana and I had to replace it with Elasticsearch-1.4.2 to get Kibana to work.

**Comment by untergeek** [comment]
There's a few things at work here, and since you haven't pasted the error you saw, I am presuming you're attempting to use Kibana 4.

1. Logstash 1.4.2 was released in July of last year.  It was bundled with the _then_ most recent version of the jar file.
1. If you're using the jar file at all, that means you're using `protocol => "node"`, which is the default 
1. Kibana4 depends on all nodes in your Elasticsearch cluster to be v1.4 or greater.  Since Logstash was spinning up a 1.1.1 node—_even though it is client only_—it fails Kibana4's test.
1. You can get around this by using `protocol => "http"` in your elasticsearch output block.

Logstash 1.5 will see all plugins independent of the Logstash core.  Updating the Elasticsearch plugin to use the most recent jar file will become much easier in the future.

Because this change is already in the associated repositories, I am closing this issue.

**Comment by Israaaaa** [comment]
I see. Thank you! That explains it.
