### ISSUE TITLE
concurrent_ruby dependency error

### ISSUE THREAD

**Issue by untergeek** [elasticsearch/logstash#2662]
I was unable to run `bin/logstash docgen`:

```
$ bin/logstash docgen -o asciidoc ~/WORK/logstash-plugins/logstash-output-elasticsearch/lib/logstash/outputs/elasticsearch.rb
LoadError: no such file to load -- concurrent_ruby
   require at org/jruby/RubyKernel.java:1071
    (root) at /Users/buh/WORK/logstash-plugins/logstash-output-elasticsearch/lib/logstash/outputs/elasticsearch.rb:6
      load at org/jruby/RubyKernel.java:1087
    (root) at /Users/buh/WORK/logstash/docs/asciidocgen.rb:1
       run at /Users/buh/WORK/logstash/lib/logstash/runner.rb:129
      each at org/jruby/RubyArray.java:1613
       run at /Users/buh/WORK/logstash/lib/logstash/runner.rb:128
      call at org/jruby/RubyProc.java:271
       run at /Users/buh/WORK/logstash/lib/logstash/runner.rb:165
      call at org/jruby/RubyProc.java:271
  generate at /Users/buh/WORK/logstash/docs/asciidocgen.rb:171
```

**Comment by suyograo** [comment]
we can workaround this by installing dev dependencies by passing a group parameter to bunder. Or `rake test:install-all` should work. Will create a new rake task for generating docs, but this is not a blocker

**Comment by ph** [comment]
The problem here is that we are asking `logstash` to interpret code in another project. This force logstash to have the same dependencies as the targeted project. The short term hack would be to run `rake test:install-all` in the logstash project to install all the plugins and their dependencies before trying to generate the doc from the target.

The long term fix is probably to extract the docs generation outside of logstash and let the plugins generate their own docs since they already have all their dependencies correctly defined.

**Comment by electrical** [comment]
This is a known thing from the beginning.
It requires the plugin + deps to be installed to process them.

**Comment by colinsurprenant** [comment]
yes, the plugin we need to generate doc for need to be *installed* so that its dependencies are also installed.  

To generate doc for a specific plugin you are working on, you can manually add this plugin in the `Gemfile` :
```ruby
gem "logstash-output-elasticsearh", :path =>  "~/WORK/logstash-plugins/logstash-output-elasticsearch"
```

and run
```sh
bin/plugin install --no-verify
```

then you should be able to generate doc.

Otherwise, to generate doc for published plugins I guess we could just install them either individually or all using:
```sh
rake plugin:install-all
```

the plugins will be in `vendor/bundle/jruby/1.9/gems/...`

or if development dependencies are needed, if we also want to run tests...
```sh
rake test:install-all
```

and run specs
```sh
rake test:plugins
```
