### ISSUE TITLE
Plugin Milestone Validation Check version 1.5.0beta1 

### ISSUE THREAD

**Issue by cognition** [elasticsearch/logstash#2679]
I installed logstash_1.5.0.beta1-1_all.deb into an Ubuntu 14.04.1 lxc 
the error I received was: 
```
 ./logstash/bin/logstash -f std_test -t
The error reported is:
  stdin must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones
```
std_test file only had consisted of 
```
input {
       stdin {
       }
}
output {
        stdout {
        }
}
```
After searching on IRC I found there was a comment regarding that fact that milestone setting in plugins was deprecated.  
Although the verification is still active. 

logstash/lib/logstash/config/mixin.rb      line 196  
````  is_valid &&= validate_milestone    ```
I commented it out, and everything started to work.  

Not sure if milestone setting is actually being removed from plugins, if it is then  you can remove old methods pertaining to it;  
** but if it isn't this is a good hack/workaround till the addition of milestone settings is replaced in the 1.5 version plugins.

**Comment by ph** [comment]
Sorry for the small hiccups, you are right the milestone option in the plugins were removed, we are also deprecating the code in master about it. We are now using the rubygems version system to let plugin owner have their own version.

I'll be closing this since it is already done, but its good fix until rc1 is released.
