### ISSUE TITLE
JSON file input shows no results

### ISSUE THREAD

**Issue by qwel3** [elasticsearch/logstash#2686]
Here is a sample from my logs in the json file

{ "_id" : ObjectId("5327dkjsd8jeiwudfe"), "field2" : "value", "field3" : "value", "ip" : "98.80.55.5"}

Here is the conf file for logstash
input {
  file {
     type => "json"
     path => "/var/log/test/*"
     codec => json
  }
}
output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    host => localhost
    codec => rubydebug
  }
}

When I start logstash

./bin/logstash -f myfile.conf

It doesn't show any results. And then I use --debug and get the following:

_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}
_discover_file_glob: /var/log/test/*: glob is: ["/var/log/test/test.json"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"117"}

**Comment by qwel3** [comment]
Whats the problem? Id appreciate your help thank you.

**Comment by jordansissel** [comment]
By default, logstash treats files as live streams, which means it starts following a file at the end. Starting with a file that is never written to, but has data already, will result in the symptoms you are seeing here - no data is read because Logstash is waiting for new data.

If you are backfilling old data, the stdin input might be easier, using `input { stdin { ... } }` and then piping your data in:

```
cat myfile.txt | bin/logstash -f myconfig
```

Alternately, if you must use the file input, you will need to do two things:
1) Tell logstash to start at the beginning of new files. This is done by setting `start_position => beginning` in the file input.
2) Remove the file that informs Logstash about files it is tracking. This file is in $HOME and can usually be removed by running `rm ~/.sincedb*` (the trailing asterisk is important)

**Comment by qwel3** [comment]
thanks. that makes sense. i really appreciate your help, so you don't recommend i remove the file sincedb ?

**Comment by markwalkom** [comment]
You can if you are testing, though it's easier if you just us stdin and then cat the file as @jordansissel mentioned, that way you don't have to always remove the file if you want to test with the same data.

**Comment by qwel3** [comment]
okay, thank you. :+1: 

:)
