### ISSUE TITLE
Error: URI scheme not supported

### ISSUE THREAD

**Issue by fandrei** [elasticsearch/logstash#2693]
I'm getting this error message when trying to start 1.5.0-beta on Windows:
```
io/console not supported; tty will not be manipulated
Error: URI scheme not supported: D:/projects/logstash-test/ParsingBenchmark/_data/benchmark.conf
Either pass a local file path or "file|http://" URI
```
or
```
io/console not supported; tty will not be manipulated
File paths must be absolute, relative path specified: file:///D:/projects/logstash-test/ParsingBenchmark/_data/*.in
```
or
```
io/console not supported; tty will not be manipulated
The error reported is:
bad URI(is not URI?): D:\projects\logstash-test\ParsingBenchmark\_data\benchmark.conf
```
So, how exactly I should format paths?

**Comment by ph** [comment]
There was a bug on the 1.5 beta preventing logstash on windows to correctly load the configuration file. 
The bug is currently fixed in master with 2 commits: https://github.com/elasticsearch/logstash/commit/786d2d2c1aa3b8a4a2f6c703a54ce447fd6a2dc5 and this https://github.com/elasticsearch/logstash/commit/7c7c0c9efe78e20ea76732ce9c24fbe741b8ecae and the related ticket is https://github.com/elasticsearch/logstash/issues/2504

We have put more effort in the master for windows support since the release of this beta and we should release RC1 shortly, but I do have an ETA for it.

If you want to try the fix you should create a new build from master.
